// Drizzle schema for the antidraw cloud database (Cloudflare D1 / SQLite).
//
// better-auth's tables (user, session, account, verification) are
// generated by its CLI into models/auth.model.ts — run `npm run auth:generate`
// after changing the auth config's plugins, never hand-edit. App tables go in
// their own models/*.model.ts and are re-exported here; they reference
// `user.id` (app-owned), never the Google account id (account.account_id).
export * from "../models/auth.model";
export * from "../models/publish.model";
