import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

// Drizzle schema for the antidraw cloud database (Cloudflare D1 / SQLite).
//
// better-auth's tables (user, session, account, verification) are generated by
// `@better-auth/cli generate` into auth.schema.ts — regenerate after changing
// the auth plugin set, never hand-edit. App tables live here.
export * from "./auth.schema";

// Server-side state for the desktop (loopback) sign-in flow. Holds the PKCE
// challenge between /api/desktop/start and /api/desktop/exchange so an
// intercepted loopback callback is useless without the verifier. Rows are
// short-lived and consumed on exchange; `state` is the CSRF/lookup key that
// round-trips through the browser.
export const desktopAuthFlow = sqliteTable(
  "desktop_auth_flow",
  {
    state: text("state").primaryKey(),
    codeChallenge: text("code_challenge").notNull(),
    redirectUri: text("redirect_uri").notNull(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  },
  (table) => [index("desktop_auth_flow_expiresAt_idx").on(table.expiresAt)],
);
